QBShared = QBShared or {}
QBShared.Vehicles = {
	--- Compacts
	["bmwm5touring"] = {
		["name"] = "BMW M5 Touring",
		["brand"] = "BMW",
		["model"] = "bmwm5touring",
		["price"] = 45900,
		["category"] = "sedans",
		["hash"] = `GetHashKey("bmwm5touring")`,
		["shop"] = "pdm",
	},	
	["gpz1100"] = {
		["name"] = "Kawasaki GPz1100",
		["brand"] = "Kawasaki",
		["model"] = "gpz1100",
		["price"] = 5500,
		["category"] = "motorcycles",
		["hash"] = `GetHashKey("gpz1100")`,
		["shop"] = "pdm",
	},
	["z1000a1"] = {
		["name"] = "Kawasaki Z1000 A1",
		["brand"] = "Kawasaki",
		["model"] = "z1000a1",
		["price"] = 6000,
		["category"] = "motorcycles",
		["hash"] = `GetHashKey("z1000a1")`,
		["shop"] = "pdm",
	},
	["bmws"] = {
		["name"] = "BMW S1000RR",
		["brand"] = "BMW",
		["model"] = "bmws",
		["price"] = 15400,
		["category"] = "motorcycles",
		["hash"] = `GetHashKey("bmws")`,
		["shop"] = "pdm",
	},
	["r6"] = {
		["name"] = "Yamaha R6",
		["brand"] = "Yamaha",
		["model"] = "r6",
		["price"] = 7500,
		["category"] = "motorcycles",
		["hash"] = `GetHashKey("r6")`,
		["shop"] = "pdm",
	},
	["africat"] = {
		["name"] = "Honda CRF1000L Africa Twin",
		["brand"] = "Honda",
		["model"] = "africat",
		["price"] = 11000,
		["category"] = "motorcycles",
		["hash"] = `GetHashKey("africat")`,
		["shop"] = "pdm",
	},
	["cbr650r"] = {
		["name"] = "Honda CBR 650R",
		["brand"] = "Honda",
		["model"] = "cbr650r",
		["price"] = 9690,
		["category"] = "motorcycles",
		["hash"] = `GetHashKey("cbr650r")`,
		["shop"] = "pdm",
	},
	["lc500"] = {
		["name"] = "Lexus LC 500",
		["brand"] = "Lexus",
		["model"] = "lc500",
		["price"] = 19000,
		["category"] = "sports",
		["hash"] = `GetHashKey("lc500")`,
		["shop"] = "pdm",
	},
	["ap2"] = {
		["name"] = "Honda S2000 AP2",
		["brand"] = "Honda",
		["model"] = "ap2",
		["price"] = 15000,
		["category"] = "sports",
		["hash"] = `GetHashKey("ap2")`,
		["shop"] = "pdm",
	},
	["gtam21"] = {
		["name"] = "Alfa Romeo Giulia GTAm",
		["brand"] = "Alfa Romeo",
		["model"] = "gtam21",
		["price"] = 70000,
		["category"] = "sports",
		["hash"] = `GetHashKey("gtam21")`,
		["shop"] = "pdm",
	},
	["stelvio"] = {
		["name"] = "Alfa Romeo Stelvio Quadrifoglio",
		["brand"] = "Alfa Romeo",
		["model"] = "stelvio",
		["price"] = 50000,
		["category"] = "sports",
		["hash"] = `GetHashKey("stelvio")`,
		["shop"] = "pdm",
	},
	["golfgti7"] = {
		["name"] = "Volkswagen Golf GTI MK7",
		["brand"] = "Wolkswagen",
		["model"] = "golfgti7",
		["price"] = 20000,
		["category"] = "sports",
		["hash"] = `GetHashKey("golfgti7")`,
		["shop"] = "pdm",
	},
	["mkvr32"] = {
		["name"] = "Golf R32 MK5",
		["brand"] = "Wolkswagen",
		["model"] = "mkvr32",
		["price"] = 15000,
		["category"] = "sports",
		["hash"] = `GetHashKey("mkvr32")`,
		["shop"] = "pdm",
	},
	["golf4"] = {
		["name"] = "Volkswagen Golf MK4",
		["brand"] = "Wolkswagen",
		["model"] = "golf4",
		["price"] = 10000,
		["category"] = "sports",
		["hash"] = `GetHashKey("golf4")`,
		["shop"] = "pdm",
	},
	["chrxfire"] = {
		["name"] = "Chrysler Crossfire SRT-6",
		["brand"] = "Chrysler",
		["model"] = "chrxfire",
		["price"] = 24000,
		["category"] = "sports",
		["hash"] = `GetHashKey("chrxfire")`,
		["shop"] = "pdm",
	},
	["lanex400"] = {
		["name"] = "Mitsubishi Lancer Evolution X FQ-400",
		["brand"] = "Mitsubishi",
		["model"] = "lanex400",
		["price"] = 50000,
		["category"] = "sports",
		["hash"] = `GetHashKey("lanex400")`,
		["shop"] = "pdm",
	},
	["mitsugto"] = {
		["name"] = "Mitsubishi 3000 GT VR4",
		["brand"] = "Mitsubishi",
		["model"] = "mitsugto",
		["price"] = 55000,
		["category"] = "sports",
		["hash"] = `GetHashKey("mitsugto")`,
		["shop"] = "pdm",
	},
	["evo9"] = {
		["name"] = "Mitsubishi Lancer Evolution IX MR",
		["brand"] = "Mitsubishi",
		["model"] = "evo9",
		["price"] = 40000,
		["category"] = "sports",
		["hash"] = `GetHashKey("evo9")`,
		["shop"] = "pdm",
	},
	["eclipsegt09"] = {
		["name"] = "Mitsubishi Eclipse GT",
		["brand"] = "Mitsubishi",
		["model"] = "eclipsegt09",
		["price"] = 29000,
		["category"] = "sports",
		["hash"] = `GetHashKey("eclipsegt09")`,
		["shop"] = "pdm",
	},
	["gsx"] = {
		["name"] = "Mitsubishi Eclipse GS-T",
		["brand"] = "Mitsubishi",
		["model"] = "gsx",
		["price"] = 13500,
		["category"] = "sports",
		["hash"] = `GetHashKey("gsx")`,
		["shop"] = "pdm",
	},
	["brz13"] = {
		["name"] = "Subaru BRZ13",
		["brand"] = "Subaru",
		["model"] = "brz13",
		["price"] = 32000,
		["category"] = "sports",
		["hash"] = `GetHashKey("brz13")`,
		["shop"] = "pdm",
	},
	["subwrx"] = {
		["name"] = "Subaru Impreza WRX STI",
		["brand"] = "Subaru",
		["model"] = "subwrx",
		["price"] = 22000,
		["category"] = "sports",
		["hash"] = `GetHashKey("subwrx")`,
		["shop"] = "pdm",
	},
	["vanquish01"] = {
		["name"] = "Aston Martin Vanquish 1th Gen",
		["brand"] = "Aston Martin",
		["model"] = "vanquish01",
		["price"] = 39000,
		["category"] = "sports",
		["hash"] = `GetHashKey("vanquish01")`,
		["shop"] = "pdm",
	},
	["mr2sw20"] = {
		["name"] = "Toyota MR2 SW20",
		["brand"] = "Toyota",
		["model"] = "mr2sw20",
		["price"] = 4000,
		["category"] = "sports",
		["hash"] = `GetHashKey("mr2sw20")`,
		["shop"] = "pdm",
	},
	["celisupra"] = {
		["name"] = "Toyota Celica Supra",
		["brand"] = "Toyota",
		["model"] = "celisupra",
		["price"] = 8500,
		["category"] = "sports",
		["hash"] = `GetHashKey("celisupra")`,
		["shop"] = "pdm",
	},
	["tsgr20"] = {
		["name"] = "Toyota Supra GR A90 MK5",
		["brand"] = "Toyota",
		["model"] = "tsgr20",
		["price"] = 70000,
		["category"] = "sports",
		["hash"] = `GetHashKey("tsgr20")`,
		["shop"] = "pdm",
	},
	["toysupmk4"] = {
		["name"] = "Toyota Supra A80 MK4",
		["brand"] = "Toyota",
		["model"] = "toysupmk4",
		["price"] = 65000,
		["category"] = "sports",
		["hash"] = `GetHashKey("toysupmk4")`,
		["shop"] = "pdm",
	},
	["maj350z"] = {
		["name"] = "Nissan Fairlady Z Z33",
		["brand"] = "Nissan",
		["model"] = "maj350z",
		["price"] = 38000,
		["category"] = "sports",
		["hash"] = `GetHashKey("maj350z")`,
		["shop"] = "pdm",
	},
	["s30"] = {
		["name"] = "Nissan Fairlady Z (S30)",
		["brand"] = "Nissan",
		["model"] = "s30",
		["price"] = 27000,
		["category"] = "sports",
		["hash"] = `GetHashKey("s30")`,
		["shop"] = "pdm",
	},
	["gtr1"] = {
		["name"] = "Nissan R35 GT-R",
		["brand"] = "Nissan",
		["model"] = "gtr1",
		["price"] = 115000,
		["category"] = "sports",
		["hash"] = `GetHashKey("gtr1")`,
		["shop"] = "pdm",
	},
	["bnr34"] = {
		["name"] = "Nissan Skyline GT-R (BNR34) RHD",
		["brand"] = "Nissan",
		["model"] = "bnr34",
		["price"] = 65000,
		["category"] = "sports",
		["hash"] = `GetHashKey("bnr34")`,
		["shop"] = "pdm",
	},
	["gxr33"] = {
		["name"] = "Nissan Skyline GTR",
		["brand"] = "Nissan",
		["model"] = "gxr33",
		["price"] = 30000,
		["category"] = "sports",
		["hash"] = `GetHashKey("gxr33")`,
		["shop"] = "pdm",
	},
	["bnr32"] = {
		["name"] = "Nissan Skyline GT-R (BNR32)",
		["brand"] = "Nissan",
		["model"] = "bnr32",
		["price"] = 16000,
		["category"] = "sports",
		["hash"] = `GetHashKey("bnr32")`,
		["shop"] = "pdm",
	},
	["svt00"] = {
		["name"] = "Ford Mustang SVT Cobra",
		["brand"] = "Ford",
		["model"] = "svt00",
		["price"] = 25500,
		["category"] = "sports",
		["hash"] = `GetHashKey("svt00")`,
		["shop"] = "pdm",
	},
	["mgt"] = {
		["name"] = "Ford Mustang GT",
		["brand"] = "Ford",
		["model"] = "mgt",
		["price"] = 45000,
		["category"] = "sports",
		["hash"] = `GetHashKey("mgt")`,
		["shop"] = "pdm",
	},
	["focusrs"] = {
		["name"] = "Ford Focus RS Arena",
		["brand"] = "Ford",
		["model"] = "focusrs",
		["price"] = 20000,
		["category"] = "sports",
		["hash"] = `GetHashKey("focusrs")`,
		["shop"] = "pdm",
	},
	["exor"] = {
		["name"] = "Chevrolet Camaro Exorcist",
		["brand"] = "Chevrolet",
		["model"] = "exor",
		["price"] = 75250,
		["category"] = "sports",
		["hash"] = `GetHashKey("exor")`,
		["shop"] = "pdm",
	},
	["stingray"] = {     
		["name"] = "2020 Corvette C8 Stingray",
		["brand"] = "Chevrolet",
		["model"] = "stingray",
		["price"] = 95000,
		["category"] = "sports",
		["hash"] = `GetHashKey("stingray")`,
		["shop"] = "pdm",
	},
	["c5z06"] = {
		["name"] = "Chevrolet Corvette C5 Z06",
		["brand"] = "Chevrolet",
		["model"] = "c5z06",
		["price"] = 19000,
		["category"] = "sports",
		["hash"] = `GetHashKey("c5z06")`,
		["shop"] = "pdm",
	},
	["cobaltss"] = {
		["name"] = "Chevrolet Cobalt SS",
		["brand"] = "Chevrolet",
		["model"] = "cobaltss",
		["price"] = 5500,
		["category"] = "sports",
		["hash"] = `GetHashKey("cobaltss")`,
		["shop"] = "pdm",
	},
	["99viper"] = {
		["name"] = "Dodge Viper GTS ACR",
		["brand"] = "Dodge",
		["model"] = "99viper",
		["price"] = 30000,
		["category"] = "sports",
		["hash"] = `GetHashKey("99viper")`,
		["shop"] = "pdm",
	},
	["viper"] = {
		["name"] = "Dodge Viper",
		["brand"] = "Dodge",
		["model"] = "viper",
		["price"] = 55480,
		["category"] = "sports",
		["hash"] = `GetHashKey("viper")`,
		["shop"] = "pdm",
	},
	["srt8f"] = {
		["name"] = "Dodge Charger LX",
		["brand"] = "Dodge",
		["model"] = "srt8f",
		["price"] = 22500,
		["category"] = "sports",
		["hash"] = `GetHashKey("srt8f")`,
		["shop"] = "pdm",
	},
	["2013rs7"] = {
		["name"] = "Audi RS7 C7",
		["brand"] = "Audi",
		["model"] = "2013rs7",
		["price"] = 52248,
		["category"] = "sports",
		["hash"] = `GetHashKey("2013rs7")`,
		["shop"] = "pdm",
	},
	["rs4"] = {
		["name"] = "Audi RS4",
		["brand"] = "Audi",
		["model"] = "rs4",
		["price"] = 25000,
		["category"] = "sports",
		["hash"] = `GetHashKey("rs4")`,
		["shop"] = "pdm",
	},
	["rs3"] = {
		["name"] = "Audi RS3 8PA",
		["brand"] = "Audi",
		["model"] = "rs3",
		["price"] = 17500,
		["category"] = "sports",
		["hash"] = `GetHashKey("rs3")`,
		["shop"] = "pdm",
	},
	["audis32"] = {
		["name"] = "Audi S3 8L",
		["price"] = 10500,
		["category"] = "sports",
		["brand"] = "Audi",
		["model"] = "audis32",
		["hash"] = `GetHashKey("audis32")`,
		["shop"] = "pdm",
	},
	["aaq4"] = {
		["name"] = "Audi A4 ABT",
		["brand"] = "Audi",
		["model"] = "aaq4",
		["price"] = 25000,
		["category"] = "sport",
		["hash"] = `GetHashKey("aaq4")`,
		["shop"] = "pdm",
	},
	["rmodrs6"] = {
		["name"] = "Audi RS6 C8",
		["brand"] = "Audi",
		["model"] = "rmodrs6",
		["price"] = 55020,
		["category"] = "sports",
		["hash"] = `GetHashKey("rmodrs6")`,
		["shop"] = "pdm",
	},
	["tts"] = {
		["name"] = "Audi TTS 8S",
		["brand"] = "Audi",
		["model"] = "tts",
		["price"] = 25300,
		["category"] = "sports",
		["hash"] = `GetHashKey("tts")`,
		["shop"] = "pdm",
	},
	["s65w222"] = {
		["name"] = "Mercedes-Benz S65 AMG W222",
		["brand"] = "Mercedes-Benz",
		["model"] = "s65w222",
		["price"] = 85200,
		["category"] = "sports",
		["hash"] = `GetHashKey("s65w222")`,
		["shop"] = "pdm",
	},
	["s63w222"] = {
		["name"] = "Mercedes-Benz S63 AMG W222",
		["brand"] = "Mercedes-Benz",
		["model"] = "s63w222",
		["price"] = 75200,
		["category"] = "sports",
		["hash"] = `GetHashKey("s63w222")`,
		["shop"] = "pdm",
	},
	["e63sdono"] = {
		["name"] = "Mercedes-AMG E63 S 4matic W213",
		["brand"] = "Mercedes-Benz",
		["model"] = "e63sdono",
		["price"] = 35350,
		["category"] = "sports",
		["hash"] = `GetHashKey("e63sdono")`,
		["shop"] = "pdm",
	},
	["b800"] = {
		["name"] = "Brabus 800",
		["brand"] = "Mercedes-Benz",
		["model"] = "b800",
		["price"] = 98800,
		["category"] = "sports",
		["hash"] = `GetHashKey("b800")`,
		["shop"] = "pdm",
	},
	["benze55"] = {
		["name"] = "Mercedes-Benz E55 AMG W211",
		["brand"] = "Mercedes-Benz",
		["model"] = "benze55",
		["price"] = 75000,
		["category"] = "sports",
		["hash"] = `GetHashKey("benze55")`,
		["shop"] = "pdm",
	},
	["c63b"] = {
		["name"] = "Mercedes-Benz C63 AMG W204 Black Series",
		["brand"] = "Mercedes-Benz",
		["model"] = "c63b",
		["price"] = 45200,
		["category"] = "sports",
		["hash"] = `GetHashKey("c63b")`,
		["shop"] = "pdm",
	},
	["a45amg"] = {
		["name"] = "Mercedes-Benz A45 AMG W176",
		["brand"] = "Mercedes-Benz",
		["model"] = "a45amg",
		["price"] = 43245,
		["category"] = "sports",
		["hash"] = `GetHashKey("a45amg")`,
		["shop"] = "pdm",
	},
	["cl65"] = {
		["name"] = "Mercedes-Benz CL65 AMG C216",
		["brand"] = "Mercedes-Benz",
		["model"] = "cl65",
		["price"] = 10520,
		["category"] = "sports",
		["hash"] = `GetHashKey("cl65")`,
		["shop"] = "pdm",
	},
	["rmodm3e36"] = {
		["name"] = "BMW M3 E36",
		["brand"] = "BMW",
		["model"] = "rmodm3e36",
		["price"] = 9520,
		["category"] = "sports",
		["hash"] = `GetHashKey("rmodm3e36")`,
		["shop"] = "pdm",
	},
	["z4bmw"] = {
		["name"] = "BMW Z4 M40I",
		["brand"] = "BMW",
		["model"] = "z4bmw",
		["price"] = 65000,
		["category"] = "sports",
		["hash"] = `GetHashKey("z4bmw")`,
		["shop"] = "pdm",
	},
	["bmci"] = {
		["name"] = "BMW M5 F90",
		["brand"] = "BMW",
		["model"] = "bmci",
		["price"] = 85200,
		["category"] = "sports",
		["hash"] = `GetHashKey("bmci")`,
		["shop"] = "pdm",
	},
	["m5e60"] = {
		["name"] = "BMW M5 E60",
		["brand"] = "BMW",
		["model"] = "m5e60",
		["price"] = 22500,
		["category"] = "sports",
		["hash"] = `GetHashKey("m5e60")`,
		["shop"] = "pdm",
	},
	["m4comp"] = {
		["name"] = "BMW M4 G82",
		["brand"] = "BMW",
		["model"] = "m4comp",
		["price"] = 78500,
		["category"] = "sports",
		["hash"] = `GetHashKey("m4comp")`,
		["shop"] = "pdm",
	},
	["f82"] = {
		["name"] = "BMW M4 F82",
		["brand"] = "BMW",
		["model"] = "f82",
		["price"] = 42500,
		["category"] = "sports",
		["hash"] = `GetHashKey("f82")`,
		["shop"] = "pdm",
	},
	["ghis2"] = {
		["name"] = "Maserati Ghibli",
		["brand"] = "Maserati",
		["model"] = "ghis2",
		["price"] = 34000,
		["category"] = "coupes",
		["hash"] = `GetHashKey("ghis2")`,
		["shop"] = "pdm",
	},
	["mgrantur"] = {
		["name"] = "Maserati GranTurismo S",
		["brand"] = "Maserati",
		["model"] = "mgrantur",
		["price"] = 33500,
		["category"] = "coupes",
		["hash"] = `GetHashKey("mgrantur")`,
		["shop"] = "pdm",
	},
	["cliors"] = {
		["name"] = "Renault Clio RS",
		["brand"] = "Renault",
		["model"] = "cliors",
		["price"] = 6800,
		["category"] = "coupes",
		["hash"] = `GetHashKey("cliors")`,
		["shop"] = "pdm",
	},
	["civic"] = {
		["name"] = "Honda Civic Si",
		["brand"] = "Honda",
		["model"] = "civic",
		["price"] = 4600,
		["category"] = "coupes",
		["hash"] = `GetHashKey("civic")`,
		["shop"] = "pdm",
	},
	["wraith"] = {
		["name"] = "Rolls Wraith",
		["brand"] = "Rolls-Royce",
		["model"] = "wraith",
		["price"] = 121300,
		["category"] = "coupes",
		["hash"] = `GetHashKey("wraith")`,
		["shop"] = "pdm",
	},
	["na6"] = {
		["name"] = "Mazda MX5 Miata",
		["brand"] = "Mazda",
		["model"] = "na6",
		["price"] = 3900,
		["category"] = "coupes",
		["hash"] = `GetHashKey("na6")`,
		["shop"] = "pdm",
	},
	["17turbo"] = {
		["name"] = "Porsche Panamera Turbo",
		["brand"] = "Porsche",
		["model"] = "17turbo",
		["price"] = 43400,
		["category"] = "coupes",
		["hash"] = `GetHashKey("17turbo")`,
		["shop"] = "pdm",
	},
	["mitstar88"] = {
		["name"] = "Mitsubishi Starion ESI-R",
		["brand"] = "Dewbauchee",
		["model"] = "mitstar88",
		["price"] = 3100,
		["category"] = "coupes",
		["hash"] = `GetHashKey("mitstar88")`,
		["shop"] = "pdm",
	},
	["ben17"] = {
		["name"] = "Bentley Supersport",
		["brand"] = "Bentley",
		["model"] = "ben17",
		["price"] = 79500,
		["category"] = "coupes",
		["hash"] = `GetHashKey("ben17")`,
		["shop"] = "pdm",
	},
	["gt86"] = {
		["name"] = "Toyota GT86",
		["brand"] = "Toyota",
		["model"] = "gt86",
		["price"] = 16200,
		["category"] = "coupes",
		["hash"] = `GetHashKey("gt86")`,
		["shop"] = "pdm",
	},
	["cats"] = {
		["name"] = "Cadillac ATS-V",
		["brand"] = "Cadillac",
		["model"] = "cats",
		["price"] = 13500,
		["category"] = "coupes",
		["hash"] = `GetHashKey("cats")`,
		["shop"] = "pdm",
	},
	["2014rs5"] = {
		["name"] = "Jugular",
		["brand"] = "Ocelot",
		["model"] = "2014rs5",
		["price"] = 80000,
		["category"] = "coupes",
		["hash"] = `GetHashKey("2014rs5")`,
		["shop"] = "pdm",
	},
	["rs5"] = {
		["name"] = "Audi RS5",
		["brand"] = "Audi",
		["model"] = "rs5",
		["price"] = 24500,
		["category"] = "coupes",
		["hash"] = `GetHashKey("rs5")`,
		["shop"] = "pdm",
	},
	["rs318"] = {
		["name"] = "Audi RS3 8VA",
		["brand"] = "Audi",
		["model"] = "rs318",
		["price"] = 24600,
		["category"] = "coupes",
		["hash"] = `GetHashKey("rs318")`,
		["shop"] = "pdm",
	},
	["brabus850"] = {
		["name"] = "Brabus 850",
		["brand"] = "Brabus",
		["model"] = "brabus850",
		["price"] = 82000,
		["category"] = "coupes",
		["hash"] = `GetHashKey("brabus850")`,
		["shop"] = "pdm",
	},
	["cla45sb"] = {
		["name"] = "Mercedes CLA45 AMG C117",
		["brand"] = "Mercedes-Benz",
		["model"] = "cla45sb",
		["price"] = 23200,
		["category"] = "coupes",
		["hash"] = `GetHashKey("cla45sb")`,
		["shop"] = "pdm",
	},
	["ae350"] = {
		["name"] = "Mercedes E350 4Matic W212",
		["brand"] = "Mercedes-Benz",
		["model"] = "ae350",
		["price"] = 16700,
		["category"] = "coupes",
		["hash"] = `GetHashKey("ae350")`,
		["shop"] = "pdm",
	},
	["600sl"] = {
		["name"] = "Mercedes 600SL R129",
		["brand"] = "Mercedes-Benz",
		["model"] = "600sl",
		["price"] = 9500,
		["category"] = "coupes",
		["hash"] = `GetHashKey("600sl")`,
		["shop"] = "pdm",
	},
	["AMGCE"] = {
		["name"] = "Mercedes 300CE AMG",
		["brand"] = "Mercedes-Benz",
		["model"] = "AMGCE",
		["price"] = 11900,
		["category"] = "coupes",
		["hash"] = `GetHashKey(AMGCE)`,
		["shop"] = "pdm",
	},
	["m6f13"] = {
		["name"] = "BMW M6 F13",
		["brand"] = "Ocelot",
		["model"] = "m6f13",
		["price"] = 44300,
		["category"] = "coupes",
		["hash"] = `GetHashKey("m6f13")`,
		["shop"] = "pdm",
	},
	["m2"] = {
		["name"] = "BMW M2",
		["brand"] = "BMW",
		["model"] = "m2",
		["price"] = 52000,
		["category"] = "coupes",
		["hash"] = `GetHashKey("m2")`,
		["shop"] = "pdm",
	},
	["bgnx"] = {
		["name"] = "Buick GNX",
		["brand"] = "Buick",
		["model"] = "bgnx",
		["price"] = 4900,
		["category"] = "muscle",
		["hash"] = `GetHashKey("bgnx")`,
		["shop"] = "pdm",
	},
	["olds442"] = {
		["name"] = "Oldsmobile 442",
		["brand"] = "Oldsmobile",
		["model"] = "olds442",
		["price"] = 24000,
		["category"] = "muscle",
		["hash"] = `GetHashKey("olds442")`,
		["shop"] = "pdm",
	},
	["gtorino76"] = {
		["name"] = "Ford Gran Torino",
		["brand"] = "Ford",
		["model"] = "gtorino76",
		["price"] = 4300,
		["category"] = "muscle",
		["hash"] = `GetHashKey("gtorino76")`,
		["shop"] = "pdm",
	},
	["mmach1"] = {
		["name"] = "Ford Mustang Mach 1",
		["brand"] = "Ford",
		["model"] = "mmach1",
		["price"] = 42000,
		["category"] = "muscle",
		["hash"] = `GetHashKey("mmach1")`,
		["shop"] = "pdm",
	},
	["taki428"] = {
		["name"] = "Shelby GT500 428CJ",
		["brand"] = "Dewbauchee",
		["model"] = "taki428",
		["price"] = 21000,
		["category"] = "muscle",
		["hash"] = `GetHashKey("taki428")`,
		["shop"] = "pdm",
	},
	["mustang68"] = {
		["name"] = "Ford Mustang Mk.2",
		["brand"] = "Ford",
		["model"] = "mustang68",
		["price"] = 30000,
		["category"] = "muscle",
		["hash"] = `GetHashKey("mustang68")`,
		["shop"] = "pdm",
	},
	["mustang65"] = {
		["name"] = "Ford Mustang Mk.1",
		["brand"] = "Ford",
		["model"] = "mustang65",
		["price"] = 32000,
		["category"] = "muscle",
		["hash"] = `GetHashKey("mustang65")`,
		["shop"] = "pdm",
	},
	["95stang"] = {
		["name"] = "Ford Mustang SN95",
		["brand"] = "Ford",
		["model"] = "95stang",
		["price"] = 21200,
		["category"] = "muscle",
		["hash"] = `GetHashKey("95stang")`,
		["shop"] = "pdm",
	},
	["93mustang"] = {
		["name"] = "Ford Mustang SVT Cobra R",
		["brand"] = "Ford",
		["model"] = "93mustang",
		["price"] = 17000,
		["category"] = "muscle",
		["hash"] = `GetHashKey("93mustang")`,
		["shop"] = "pdm",
	},
	["21camaro"] = {
		["name"] = "Chevrolet Camaro 2021",
		["brand"] = "Chevrolet",
		["model"] = "21camaro",
		["price"] = 68000,
		["category"] = "muscle",
		["hash"] = `GetHashKey("21camaro")`,
		["shop"] = "pdm",
	},
	["zl12017"] = {
		["name"] = "Chevrolet Camaro ZL1 2017",
		["brand"] = "Chevrolet",
		["model"] = "zl12017",
		["price"] = 42000,
		["category"] = "muscle",
		["hash"] = `GetHashKey("zl12017")`,
		["shop"] = "pdm",
	},
	["montecarlo"] = {
		["name"] = "Chevrolet Monte Carlo",
		["brand"] = "Chevrolet",
		["model"] = "montecarlo",
		["price"] = 15000,
		["category"] = "muscle",
		["hash"] = `GetHashKey("montecarlo")`,
		["shop"] = "pdm",
	},
	["camaro70"] = {
		["name"] = "Neo",
		["brand"] = "Chevrolet",
		["model"] = "camaro70",
		["price"] = 25000,
		["category"] = "muscle",
		["hash"] = `GetHashKey("camaro70")`,
		["shop"] = "pdm",
	},
	["69charger"] = {
		["name"] = "Dodge Charger 2th Gen",
		["brand"] = "Truffade",
		["model"] = "69charger",
		["price"] = 27000,
		["category"] = "muscle",
		["hash"] = `GetHashKey("69charger")`,
		["shop"] = "pdm",
	},
	["challenger"] = {   
		["name"] = "Dodge Challanger",
		["brand"] = "Dodge",
		["model"] = "challenger",
		["price"] = 23000,
		["category"] = "muscle",
		["hash"] = `GetHashKey("challenger")`,
		["shop"] = "pdm",
	},
	["lx2018"] = {
		["name"] = "Lexus LX570",
		["brand"] = "Lexus",
		["model"] = "lx2018",
		["price"] = 36000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("lx2018")`,
		["shop"] = "pdm",
	},
	["r50"] = {
		["name"] = "Volkswagen Touareg R50",
		["brand"] = "Volkswagen",
		["model"] = "r50",
		["price"] = 16200,
		["category"] = "suvs",
		["hash"] = `GetHashKey("r50")`,
		["shop"] = "pdm",
	},
	["hummer"] = {
		["name"] = "Hummer H1",
		["brand"] = "Hummer",
		["model"] = "hummer",
		["price"] = 6500,
		["category"] = "suvs",
		["hash"] = `GetHashKey("hummer")`,
		["shop"] = "pdm",
	},
	["jeep2012"] = {
		["name"] = "Jeep Wrangler",
		["brand"] = "Jeep ",
		["model"] = "jeep2012",
		["price"] = 6000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("jeep2012")`,
		["shop"] = "pdm",
	},
	["trhawk1"] = {
		["name"] = "Jeep Grand Cherokee Trackhawk",
		["brand"] = "Jeep",
		["model"] = "trhawk1",
		["price"] = 22000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("trhawk1")`,
		["shop"] = "pdm",
	},
	["rubi3d"] = {
		["name"] = "Jeep Wrangler Rubicon",
		["brand"] = "Jeep",
		["model"] = "rubi3d",
		["price"] = 5500,
		["category"] = "suvs",
		["hash"] = `GetHashKey("rubi3d")`,
		["shop"] = "pdm",
	},
	["pm19"] = {
		["name"] = "Porsche Macan Turbo",
		["brand"] = "Porsche",
		["model"] = "pm19",
		["price"] = 35400,
		["category"] = "suvs",
		["hash"] = `GetHashKey("pm19")`,
		["shop"] = "pdm",
	},
	["pcs18"] = {
		["name"] = "Porsche Cayenne Turbo S 2018",
		["brand"] = "Vapid",
		["model"] = "pcs18",
		["price"] = 39500,
		["category"] = "suvs",
		["hash"] = `GetHashKey("pcs18")`,
		["shop"] = "pdm",
	},
	["pct13"] = {
		["name"] = "Porsche Cayenne Turbo 2013",
		["brand"] = "Porsche",
		["model"] = "pct13",
		["price"] = 21600,
		["category"] = "suvs",
		["hash"] = `GetHashKey("pct13")`,
		["shop"] = "pdm",
	},
	["evoque"] = {
		["name"] = "Range Rover Evoque",
		["brand"] = "Range Rover",
		["model"] = "evoque",
		["price"] = 19000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("evoque")`,
		["shop"] = "pdm",
	},
	["vogue"] = {
		["name"] = "Range Rover Vogue 4th Gen",
		["brand"] = "Range Rover",
		["model"] = "vogue",
		["price"] = 16000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("vogue")`,
		["shop"] = "pdm",
	},
	["rrab"] = {
		["name"] = "Range Rover SV Autobiography Dynamic",
		["brand"] = "Range Rover",
		["model"] = "rrab",
		["price"] = 25000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("rrab")`,
		["shop"] = "pdm",
	},
	["rrs08"] = {
		["name"] = "Range Rover Supercharged",
		["brand"] = "Range Rover",
		["model"] = "rrs08",
		["price"] = 8500,
		["category"] = "suvs",
		["hash"] = `GetHashKey("rrs08")`,
		["shop"] = "pdm",
	},
	["rsvr16"] = {
		["name"] = "Range Rover Sport SVR",
		["brand"] = "Range Rover",
		["model"] = "rsvr16",
		["price"] = 13700,
		["category"] = "suvs",
		["hash"] = `GetHashKey("rsvr16")`,
		["shop"] = "pdm",
	},
	["rrst"] = {
		["name"] = "Range Rover Vogue Startech",
		["brand"] = "Range Rover",
		["model"] = "rrst",
		["price"] = 32000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("rrst")`,
		["shop"] = "pdm",
	},
	["bentayga17"] = {
		["name"] = "Bentley Bentayga",
		["brand"] = "Bentley",
		["model"] = "bentayga17",
		["price"] = 57000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("bentayga17")`,
		["shop"] = "pdm",
	},
	["yukonxl"] = {
		["name"] = "GMC Yukon XL",
		["brand"] = "Vapid",
		["model"] = "yukonxl",
		["price"] = 9000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("yukonxl")`,
		["shop"] = "pdm",
	},
	["Suburban"] = {
		["name"] = "GMC Suburban 7th Gen",
		["brand"] = "GMC",
		["model"] = "Suburban",
		["price"] = 2900,
		["category"] = "suvs",
		["hash"] = `GetHashKey("Suburban")`,
		["shop"] = "pdm",
	},
	["gmcyd"] = {
		["name"] = "GMC Yukon Denali",
		["brand"] = "GMC",
		["model"] = "gmcyd",
		["price"] = 50000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("gmcyd")`,
		["shop"] = "pdm",
	},
	["lc100"] = {
		["name"] = "Toyota Landcruiser 100",
		["brand"] = "Bravado",
		["model"] = "lc100",
		["price"] = 3500,
		["category"] = "suvs",
		["hash"] = `GetHashKey("lc100")`,
		["shop"] = "pdm",
	},
	["sclkuz"] = {
		["name"] = "Toyota Land Cruiser 200 (c) HAKAMA",
		["brand"] = "Vapid",
		["model"] = "sclkuz",
		["price"] = 11000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("sclkuz")`,
		["shop"] = "pdm",
	},
	["4runner"] = {
		["name"] = "Toyota 4Runner",
		["brand"] = "Maibatsu",
		["model"] = "4runner",
		["price"] = 5300,
		["category"] = "suvs",
		["hash"] = `GetHashKey("4runner")`,
		["shop"] = "pdm",
	},
	["rav4"] = {
		["name"] = "Toyota RAV4",
		["brand"] = "Toyota",
		["model"] = "rav4",
		["price"] = 4000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("rav4")`,
		["shop"] = "pdm",
	},
	["fjcruiser"] = {
		["name"] = "Toyota FJ Cruiser",
		["brand"] = "Toyota",
		["model"] = "fjcruiser",
		["price"] = 3000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("fjcruiser")`,
		["shop"] = "pdm",
	},
	["escalade"] = {
		["name"] = 'Cadillac Escalade', 
		["brand"] = "Cadilac",
		["price"] = 17499,
		["category"] = "suvs",
		["model"] = "escalade",
		["hash"] = `GetHashKey("escalade")`,
		["shop"] = "pdm",
	},
	["explorer"] = {
		["name"] = "Ford Explorer",
		["brand"] = "Ford",
		["model"] = "explorer",
		["price"] = 24400,
		["category"] = "suvs",
		["hash"] = `GetHashKey("explorer")`,
		["shop"] = "pdm",
	},
	["explorer20"] = {
		["name"] = "Ford Explorer Facelift",
		["brand"] = "Ford",
		["model"] = "explorer20",
		["price"] = 39500,
		["category"] = "suvs",
		["hash"] = `GetHashKey("explorer20")`,
		["shop"] = "pdm",
	},
	["sbban"] = {
		["name"] = "Chevrolet Suburban Z71",
		["brand"] = "Chevrolet",
		["model"] = "sbban",
		["price"] = 7000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("sbban")`,
		["shop"] = "pdm",
	},
	["csuburban"] = {
		["name"] = "Chevrolet Suburban 7th Gen",
		["brand"] = "Benefactor",
		["model"] = "csuburban",
		["price"] = 4000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("csuburban")`,
		["shop"] = "pdm",
	},
	["SUBN"] = {
		["name"] = "Chevrolet Suburban",
        ["brand"] = "Chevrolet",
		["model"] = "SUBN",
		["price"] = 14000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("SUBN")`,
		["shop"] = "pdm",
	},
	["bc21tahoes"] = {
		["name"] = "Seminole Frontier",
		["brand"] = "Canis",
		["model"] = "seminole2",
		["price"] = 15000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("gle53")`,
		["shop"] = "pdm",
	},
	["tahoe1"] = {
		["name"] = "Chevrolet Tahoe",
		["brand"] = "Chevrolet",
		["model"] = "tahoe1",
		["price"] = 13000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("tahoe1")`,
		["shop"] = "pdm",
	},
	["q820"] = {
		["name"] = "Audi Q8",
		["brand"] = "Audi",
		["model"] = "q820",
		["price"] = 68100,
		["category"] = "suvs",
		["hash"] = `GetHashKey("q820")`,
		["shop"] = "pdm",
	},
	["Q7"] = {
		["name"] = "Audi Q7",
		["brand"] = "Audi ",
		["model"] = "Q7",
		["price"] = 64000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("Q7")`,
		["shop"] = "pdm",
	},
	["gle450"] = {
		["name"] = "Mercedes GLE450 AMG W166",
		["brand"] = "Mercedes-Benz",
		["model"] = "gle450",
		["price"] = 67200,
		["category"] = "suvs",
		["hash"] = `GetHashKey("gle450")`,
		["shop"] = "pdm",
	},
	["gl63"] = {
		["name"] = "Mercedes GL63 AMG X166",
		["brand"] = "Mercedes-Benz",
		["model"] = "gl63",
		["price"] = 30000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("gl63")`,
		["shop"] = "pdm",
	},
	["gls63"] = {
		["name"] = "Mercedes GLS63 AMG X166",
		["brand"] = "Mercedes-Benz",
		["model"] = "gls63",
		["price"] = 40000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("gls63")`,
		["shop"] = "pdm",
	},
	["XG632019"] = {
		["name"] = "Mercedes G63 AMG Edition One",
		["brand"] = "Mercedes-Benz",
		["model"] = "XG632019",
		["price"] = 60000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("XG632019")`,
		["shop"] = "pdm",
	},
	["g632019"] = {
		["name"] = "Mercedes G63 AMG",
		["brand"] = "Mercedes-Benz",
		["model"] = "g632019",
		["price"] = 50000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("g632019")`,
		["shop"] = "pdm",
	},
	["g65"] = {
		["name"] = "Mercedes G65 AMG",
		["brand"] = "Mercedes-Benz",
		["model"] = "g65",
		["price"] = 55000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("g65")`,
		["shop"] = "pdm",
	},
	["gle53"] = {
		["name"] = "Mercedes GLE53 AMG X166",
		["brand"] = "Mercedes-Benz",
		["model"] = "gle53",
		["price"] = 79000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("gle53")`,
		["shop"] = "pdm",
	},
	["mlbrabus"] = {
		["name"] = "Mercedes ML55 Brabus",
		["brand"] = "Mercedes-Benz",
		["model"] = "mlbrabus",
		["price"] = 13500,
		["category"] = "suvs",
		["hash"] = `GetHashKey("mlbrabus")`,
		["shop"] = "pdm",
	},
	["bmwg07"] = {
		["name"] = "BMW X7 M50i",
		["brand"] = "BMW",
		["model"] = "bmwg07",
		["price"] = 53000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("bmwg07")`,
		["shop"] = "pdm",
	},
	["rmodx6"] = {
		["name"] = "BMW X6M F16 Breitbau",
		["brand"] = "BMW",
		["model"] = "rmodx6",
		["price"] = 39000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("rmodx6")`,
		["shop"] = "pdm",
	},
	["x6m"] = {
		["name"] = "BMW X6 F16",
		["brand"] = "BMW",
		["model"] = "x6m",
		["price"] = 37000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("x6m")`,
		["shop"] = "pdm",
	},
	["x5om"] = {
		["name"] = "BMW X5 30D XDRIVE",
		["brand"] = "BMW",
		["model"] = "x5om",
		["price"] = 36600,
		["category"] = "suvs",
		["hash"] = `GetHashKey("x5om")`,
		["shop"] = "pdm",
	},
	["x5e53"] = {
		["name"] = "BMW X5 E53",
		["brand"] = "BMW",
		["model"] = "x5e53",
		["price"] = 8000,
		["category"] = "suvs",
		["hash"] = `GetHashKey("x5e53")`,
		["shop"] = "pdm",
	},
	["mqgts"] = {
		["name"] = "Maserati Quattroporte GTS",
		["brand"] = "Maserati",
		["model"] = "mqgts",
		["price"] = 89100,
		["category"] = "sedans",
		["hash"] = `GetHashKey("mqgts")`,
		["shop"] = "pdm",
	},
	["lexgf350f"] = {
		["name"] = "Lexus GS 350 F SPORT",
		["brand"] = "Lexus",
		["model"] = "lexgf350f",
		["price"] = 18500,
		["category"] = "sedans",
		["hash"] = `GetHashKey("lexgf350f")`,
		["shop"] = "pdm",
	},
	["ARgiulia"] = {
		["name"] = "Alfa Romeo Giulia",
		["brand"] = "Alfa Romeo",
		["model"] = "ARgiulia",
		["price"] = 40000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("ARgiulia")`,
		["shop"] = "pdm",
	},
	["mk7"] = {
		["name"] = "Volkswagen Golf MK7",
		["brand"] = "Volkswagen",
		["model"] = "mk7",
		["price"] = 180000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("mk7")`,
		["shop"] = "pdm",
	},
	["passat"] = {
		["name"] = "Volkswagen Passat B8",
		["brand"] = "Volkswagen",
		["model"] = "passat",
		["price"] = 18000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("passat")`,
		["shop"] = "pdm",
	},
	["volvo850r"] = {
		["name"] = "Volvo 850R",
		["brand"] = "Volvo",
		["model"] = "volvo850r",
		["price"] = 11000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("volvo850r")`,
		["shop"] = "pdm",
	},
	["rrphantom"] = {
		["name"] = "Rolls-Royce Phantom",
		["brand"] = "Rolls-Royce",
		["model"] = "rrphantom",
		["price"] = 300000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("rrphantom")`,
		["shop"] = "pdm",
	},
	["chry300"] = {
		["name"] = "Chysler 300CC SRT8",
		["brand"] = "Chysler",
		["model"] = "chry300",
		["price"] = 25000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("chry300")`,
		["shop"] = "pdm",
	},
	["300srt8"] = {
		["name"] = "Chrysler 300 SRT8",
		["brand"] = "Chrysler",
		["model"] = "300srt8",
		["price"] = 36300,
		["category"] = "sedans",
		["hash"] = `GetHashKey("300srt8")`,
		["shop"] = "pdm",
	},
	["mz3"] = {
		["name"] = "Mazda MZ3",
		["brand"] = "Mazda",
		["model"] = "mz3",
		["price"] = 6000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("mz3")`,
		["shop"] = "pdm",
	},
	["bmm"] = {
		["name"] = "Bentley Mulsanne Mulliner",
		["brand"] = "Bentley",
		["model"] = "bmm",
		["price"] = 70000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("bmm")`,
		["shop"] = "pdm",
	},
	["r31"] = {
		["name"] = "Nissan Skyline GTS-R R31",
		["brand"] = "Nissan",
		["model"] = "r31",
		["price"] = 45000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("r31")`,
		["shop"] = "pdm",
	},
	["ctsv"] = {
		["name"] = "Cadilac CTS-V 2th gen",
		["model"] = "ctsv",
		["price"] = 25000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("ctsv")`,
		["shop"] = "pdm",
	},
	["ctsv16"] = {
		["name"] = "Cadilac CTS-V 3th gen",
		["brand"] = "sedans",
		["model"] = "ctsv16",
		["price"] = 30000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("ctsv16")`,
		["shop"] = "pdm",
	},
	["crownPL"] = {
		["name"] = "Ford Crown Victoria",
		["brand"] = "Ford",
		["model"] = "crownPL",
		["price"] = 10000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("crownPL")`,
		["shop"] = "pdm",
	},
	["caprice89"] = {
		["name"] = "Chevrolet Caprice 3th gen",
		["brand"] = "Chevrolet",
		["model"] = "caprice89",
		["price"] = 2000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("caprice89")`,
		["shop"] = "pdm",
	},
	["85impala"] = {
		["name"] = "Chevrolet Impala 6th gen",
		["brand"] = "Chevrolet",
		["model"] = "85impala",
		["price"] = 2000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("85impala")`,
		["shop"] = "pdm",
	},
	["caprice12"] = {
		["name"] = "Chevrolet Caprice 6th gen",
		["brand"] = "Chevrolet",
		["model"] = "caprice12",
		["price"] = 4100,
		["category"] = "sedans",
		["hash"] = `GetHashKey("caprice12")`,
		["shop"] = "pdm",
	},
	["rs6sedan"] = {
		["name"] = 'Audi RS6 C6', 
		["brand"] = "Audi",
		["price"] = 25000,
		["category"] = "sedans",
		["model"] = "rs6sedan",
		["hash"] = `GetHashKey("rs6sedan")`,
		["shop"] = "pdm",
	},
	["audirs4"] = {
		["name"] = "Audi RS4 B5",
		["brand"] = "Audi",
		["model"] = "audirs4",
		["price"] = 20000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("audirs4")`,
		["shop"] = "pdm",
	},
	["a6"] = {
		["name"] = 'Audi A6', 
		["brand"] = "Audi",
		["price"] = 32000,
		["category"] = "sedans",
		["model"] = "a6",
		["hash"] = `GetHashKey("a6")`,
		["shop"] = "pdm",
	},
	["s3sedan"] = {
		["name"] = "Audi S3",
		["brand"] = "Audi",
		["model"] = "s3sedan",
		["price"] = 25000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("s3sedan")`,
		["shop"] = "pdm",
	},
	["a8audi"] = {
		["name"] = "Audi A8 W12",
		["brand"] = "Audi",
		["model"] = "a8audi",
		["price"] = 9800,
		["category"] = "muscle",
		["hash"] = `GetHashKey("a8audi")`,
		["shop"] = "pdm",
	},
	["c5rs6"] = {
		["name"] = "Audi RS6 C5",
		["brand"] = "Audi",
		["model"] = "c5rs6",
		["price"] = 12000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("c5rs6")`,
		["shop"] = "pdm",
	},
	["audirs6tk"] = {
		["name"] = "Audi RS6 C7",
		["brand"] = "Audi",
		["model"] = "audirs6tk",
		["price"] = 60000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("audirs6tk")`,
		["shop"] = "pdm",
	},
	["s63amg"] = {
		["name"] = "Mercedes S63 AMG W222",
		["brand"] = "Mercedes-Benz",
		["model"] = "s63amg",
		["price"] = 40000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("s63amg")`,
		["shop"] = "pdm",
	},
	["e63amg"] = {
		["name"] = "Mercedes E63s AMG W212",
		["brand"] = "Mercedes-Benz",
		["model"] = "e63amg",
		["price"] = 30000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("e63amg")`,
		["shop"] = "pdm",
	},
	["brabus8501"] = {
		["name"] = "Brabus 850 S-Class",
		["brand"] = "Brabus",
		["model"] = "brabus8501",
		["price"] = 90000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("brabus8501")`,
		["shop"] = "pdm",
	},
	["s600w220"] = {
		["name"] = 'Mercedes S600 W220', 
		["brand"] = "Mercedes-Benz",
		["price"] = 16000,
		["category"] = "sedans",
		["model"] = "s600w220",
		["hash"] = `GetHashKey("s600w220")`,
		["shop"] = "pdm",
	},
	["s500w222"] = {
		["name"] = "Mercedes S500 W222",
		["brand"] = "Mercedes-Benz",
		["model"] = "s500w222",
		["price"] = 49000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("s500w222")`,
		["shop"] = "pdm",
	},
	["w210amg"] = {
		["name"] = "Mercedes E55 AMG W210",
		["brand"] = "Mercedes-Benz",
		["model"] = "w210amg",
		["price"] = 10000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("w210amg")`,
		["shop"] = "pdm",
	},
	["w210"] = {
		["name"] = 'Mercedes E320', 
		["brand"] = "Mercedes-Benz",
		["price"] = 8000,
		["category"] = "sedans",
		["model"] = "w210",
		["hash"] = `GetHashKey("c32")`,
		["shop"] = "pdm",
	},
	["w140"] = {
		["name"] = "Mercedes W140 AMG",
		["brand"] = "Mercedes-Benz",
		["model"] = "w140",
		["price"] = 5500,
		["category"] = "sedans",
		["hash"] = `GetHashKey("w140")`,
		["shop"] = "pdm",
	},
	["mercw126"] = {
		["name"] = "Mercedes 560 SEL W126",
		["brand"] = "Mercedes-Benz",
		["model"] = "mercw126",
		["price"] = 7000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("mercw126")`,
		["shop"] = "pdm",
	},
	["600sel"] = {
		["name"] = "Mercedes 600 SEL W140",
		["brand"] = "Mercedes-Benz",
		["model"] = "600sel",
		["price"] = 5000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("600sel")`,
		["shop"] = "pdm",
	},
	["c63w205"] = {
		["name"] = "Mercedes C63 AMG W205",
		["brand"] = "Mercedes-Benz",
		["model"] = "c63w205",
		["price"] = 60000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("c63w205")`,
		["shop"] = "pdm",
	},
	["c6320"] = {
		["name"] = "Mercedes C63 AMG W205 2016",
		["brand"] = "Mercedes-Benz",
		["model"] = "c6320",
		["price"] = 47000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("c6320")`,
		["shop"] = "pdm",
	},
	["c63a"] = {
		["name"] = "Mercedes C63 AMG W204",
		["brand"] = "Mercedes-Benz",
		["model"] = "c63a",
		["price"] = 32000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("c63a")`,
		["shop"] = "pdm",
	},
	
	----------MUST BE ENABLED FOR THE BELOW VEHICLES-------------+set sv_enforceGameBuild 2372-------------------------------
	----------MUST BE ENABLED FOR THE BELOW VEHICLES-------------+set sv_enforceGameBuild 2372-------------------------------
	----------MUST BE ENABLED FOR THE BELOW VEHICLES-------------+set sv_enforceGameBuild 2372-------------------------------
	----------MUST BE ENABLED FOR THE BELOW VEHICLES-------------+set sv_enforceGameBuild 2372-------------------------------
	----------MUST BE ENABLED FOR THE BELOW VEHICLES-------------+set sv_enforceGameBuild 2372-------------------------------
	----------MUST BE ENABLED FOR THE BELOW VEHICLES-------------+set sv_enforceGameBuild 2372-------------------------------
	----------MUST BE ENABLED FOR THE BELOW VEHICLES-------------+set sv_enforceGameBuild 2372-------------------------------
	----------MUST BE ENABLED FOR THE BELOW VEHICLES-------------+set sv_enforceGameBuild 2372-------------------------------

	["c32"] = {
		["name"] = "Mercedes C32 AMG",
		["brand"] = "Mercedes-Benz",
		["model"] = "c32",
		["price"] = 16000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("c32")`,
		["shop"] = "pdm",
	},
	["e34"] = {
		["name"] = "BMW M5 E34",
		["brand"] = "BMW",
		["model"] = "e34",
		["price"] = 19000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("e34")`,
		["shop"] = "pdm",
	},
	["mteche39"] = {
		["name"] = "BMW 530D E39",
		["brand"] = "BMW",
		["model"] = "mteche39",
		["price"] = 12100,
		["category"] = "sedans",
		["hash"] = `GetHashKey("mteche39")`,
		["shop"] = "pdm",
	},
	["325e"] = {
		["name"] = "BMW 325e E30",
		["brand"] = "BMW",
		["model"] = "325e",
		["price"] = 7500,
		["category"] = "sedans",
		["hash"] = `GetHashKey("325e")`,
		["shop"] = "pdm",
	},
	["745le"] = {
		["name"] = "BMW 745le xDrive",
		["brand"] = "BMW",
		["model"] = "745le",
		["price"] = 70000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("745le")`,
		["shop"] = "pdm",
	},
	["bmwg20"] = {
		["name"] = "BMW G20",
		["brand"] = "BMW",
		["model"] = "bmwg20",
		["price"] = 40000,
		["category"] = "sedans",
		["hash"] = `GetHashKey("bmwg20")`,
		["shop"] = "pdm",
	},
	["m3f80"] = {
		["name"] = "BMW M3 F80",
		["brand"] = "BMW",
		["model"] = "m3f80",
		["price"] = 64000,
		["category"] = "sports",
		["hash"] = `GetHashKey("ek9")`,
		["shop"] = "pdm",
	},
	["bmw1"] = {
		["name"] = "BMW 1 Serie",
		["brand"] = "BMW",
		["model"] = "bmw1",
		["price"] = 4200,
		["category"] = "sedans",
		["hash"] = `GetHashKey("bmw1")`,
		["shop"] = "pdm",
	},
	["fk8"] = {
		["name"] = "Honda Civic Type-R FK8",
		["brand"] = "Honda",
		["model"] = "fk8",
		["price"] = 33300,
		["category"] = "compacts",
		["hash"] = `GetHashKey("fk8")`,
		["shop"] = "pdm",
	},
	["ek9"] = {
		["name"] = "Honda Civic Type-R EK9",
		["brand"] = "Honda",
		["model"] = "ek9",
		["price"] = 6000,
		["category"] = "compacts",
		["hash"] = `GetHashKey("ek9")`,
		["shop"] = "pdm",
	},
	["golf7r"] = {
		["name"] = "Volkswagen Golf R MK7",
		["brand"] = "Volkswagen",
		["model"] = "golf7r",
		["price"] = 19100,
		["category"] = "sports",
		["hash"] = `GetHashKey("golf7r")`,
		["shop"] = "pdm",
	},
	["golfold"] = {
		["name"] = "Volkswagen Golf GTI MK5",
		["brand"] = "Volkswagen",
		["model"] = "golfold",
		["price"] = 10700,
		["category"] = "compacts",
		["hash"] = `GetHashKey("golfold")`,
		["shop"] = "pdm",
	},
	["cooper15"] = {
		["name"] = "Mini Cooper S",
		["brand"] = "Mini",
		["model"] = "cooper15",
		["price"] = 23000,
		["category"] = "compacts",
		["hash"] = `GetHashKey("cooper15")`,
		["shop"] = "pdm",
	},
	["206"] = {
		["name"] = "Peugeot 206 GTI",
		["brand"] = "Peugeot",
		["model"] = "206",
		["price"] = 5500,
		["category"] = "compacts",
		["hash"] = `GetHashKey("206")`,
		["shop"] = "pdm",
	},
	["punto"] = {
		["name"] = "Fiat Punto",
		["brand"] = "Fiat",
		["model"] = "punto",
		["price"] = 8000,
		["category"] = "compacts",
		["hash"] = `GetHashKey("punto")`,
		["shop"] = "pdm",
	},
	["nissunny"] = {
		["name"] = "Nissan Sunny",
		["brand"] = "Nissan",
		["model"] = "nissunny",
		["price"] = 4000,
		["category"] = "compacts",
		["hash"] = `GetHashKey("nissunny")`,
		["shop"] = "pdm",
	},
	["m135i"] = {
		["name"] = "BMW M135i",
		["brand"] = "BMW",
		["model"] = "m135i",
		["price"] = 27000,
		["category"] = "compacts",
		["hash"] = `GetHashKey("m135i")`,
		["shop"] = "pdm",
	},
}